### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by 0vm** [tugonbob/heic-to-jpeg#1]
Traceback (most recent call last):
  File "D:\Downloads\heic-to-jpeg-main\heic-to-jpeg-main\main.py", line 70, in <module>
    convert_dir_heic_to_jpg(args.path, args.replace)
  File "D:\Downloads\heic-to-jpeg-main\heic-to-jpeg-main\main.py", line 54, in convert_dir_heic_to_jpg
    heic_to_jpg(heic_path)
  File "D:\Downloads\heic-to-jpeg-main\heic-to-jpeg-main\main.py", line 17, in heic_to_jpg
    image = Image.frombytes(
            ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 2969, in frombytes
    im.frombytes(data, decoder_name, args)
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 826, in frombytes
    s = d.decode(data)
        ^^^^^^^^^^^^^^
TypeError: argument 1 must be read-only bytes-like object, not memoryview

**Comment by 0vm** [comment]
cmon this was meant to be the 1 day i dont have to code



check your pull requests.

**Comment by 0vm** [comment]
btw its a windows issue.

**Comment by joshuakgao** [comment]
Good catch, thanks for the improvement.
